// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	indexer "github.com/pokt-foundation/pocket-indexer-lib"
)

type BlocksResponse struct {
	Blocks     []*indexer.Block `json:"blocks"`
	PageCount  int              `json:"pageCount"`
	Page       int              `json:"page"`
	TotalPages int              `json:"totalPages"`
}

type TransactionsResponse struct {
	Transactions []*indexer.Transaction `json:"transactions"`
	PageCount    int                    `json:"pageCount"`
	Page         int                    `json:"page"`
	TotalPages   int                    `json:"totalPages"`
}
